/** HTTP contract shared with explorer.kovanica.online (kovanica-testnet). */
import { 
  LIVE_EXPLORER, 
  LIVE_WALLET, 
  LIVE_MAP, 
  LIVE_KOVI, 
  LIVE_SITE, 
  NETWORK_ID, 
  MAINNET_ID, 
  NETWORK_PROXIES, 
  TOKEN, 
  ATOM, 
  DECIMALS, 
  SUBSIDY, 
  FOUNDER_AMOUNT, 
  FOUNDER_SEED, 
  HALVING_ERA, 
  MAX_SUPPLY, 
  MIN_FEE, 
  K, 
  TREASURY,
  getSpecText,
  isPublicSource,
  isNativeAsset,
  assetLabel,
  type AssetIdHex,
  type LocalSource,
  type PublicSource,
  type ApiSource,
  type ApiOutput,
  type ApiTx,
  type ApiDagBlock,
  type ApiUtxo,
  type ApiHistoryTx,
  type ApiNode,
  type ApiState,
  type ApiHead,
  type ApiBootstrap,
  type ApiUtxos,
  type ApiHistory,
  type ApiPrepare,
  type ApiSubmit,
  type ApiOrigins,
  type ReadOnlyPaths,
  type WriteOnlyPaths,
  READ_PATHS,
  WRITE_PATHS,
} from "../networkConstants";
import { detectNetwork } from "../network";

// Re-export the types and constants for backward compatibility
export {
  LIVE_EXPLORER,
  LIVE_WALLET,
  LIVE_MAP,
  LIVE_KOVI,
  LIVE_SITE,
  NETWORK_ID,
  MAINNET_ID,
  NETWORK_PROXIES,
  TOKEN,
  ATOM,
  DECIMALS,
  SUBSIDY,
  FOUNDER_AMOUNT,
  FOUNDER_SEED,
  HALVING_ERA,
  MAX_SUPPLY,
  MIN_FEE,
  K,
  TREASURY,
  getSpecText,
  isPublicSource,
  isNativeAsset,
  assetLabel,
  type AssetIdHex,
  type LocalSource,
  type PublicSource,
  type ApiSource,
  type ApiOutput,
  type ApiTx,
  type ApiDagBlock,
  type ApiUtxo,
  type ApiHistoryTx,
  type ApiNode,
  type ApiState,
  type ApiHead,
  type ApiBootstrap,
  type ApiUtxos,
  type ApiHistory,
  type ApiPrepare,
  type ApiSubmit,
  type ApiOrigins,
  type ReadOnlyPaths,
  type WriteOnlyPaths,
  READ_PATHS,
  WRITE_PATHS,
};

/**
 * Returns the spec text for the current network (detected via hostname).
 * This is the function to use in the app to get the spec text for the current network.
 */
export function getCurrentSpecText(): string {
  return getSpecText(detectNetwork());
}
