import { CATALOG_BY_ISO3, type CountryMeta } from "./catalog";

type Origin = { iso3: string; name: string };

const TZ_TO_ISO3: Record<string, string> = {
  "Europe/Zagreb": "HRV",
  "Europe/Belgrade": "SRB",
  "Europe/Ljubljana": "SVN",
  "Europe/Sarajevo": "BIH",
  "Europe/Skopje": "MKD",
  "Europe/Podgorica": "SRB",
  "Europe/Berlin": "DEU",
  "Europe/Paris": "FRA",
  "Europe/London": "GBR",
  "Europe/Dublin": "IRL",
  "Europe/Amsterdam": "NLD",
  "Europe/Brussels": "BEL",
  "Europe/Luxembourg": "LUX",
  "Europe/Zurich": "CHE",
  "Europe/Vienna": "AUT",
  "Europe/Rome": "ITA",
  "Europe/Madrid": "ESP",
  "Europe/Lisbon": "PRT",
  "Europe/Stockholm": "SWE",
  "Europe/Oslo": "NOR",
  "Europe/Copenhagen": "DNK",
  "Europe/Helsinki": "FIN",
  "Europe/Warsaw": "POL",
  "Europe/Prague": "CZE",
  "Europe/Budapest": "HUN",
  "Europe/Bucharest": "ROU",
  "Europe/Sofia": "BGR",
  "Europe/Athens": "GRC",
  "Europe/Istanbul": "TUR",
  "Europe/Kiev": "UKR",
  "Europe/Kyiv": "UKR",
  "Europe/Moscow": "RUS",
  "Europe/Riga": "LVA",
  "Europe/Vilnius": "LTU",
  "Europe/Tallinn": "EST",
  "Europe/Reykjavik": "ISL",
  "Atlantic/Reykjavik": "ISL",
  "America/New_York": "USA",
  "America/Chicago": "USA",
  "America/Denver": "USA",
  "America/Los_Angeles": "USA",
  "America/Phoenix": "USA",
  "America/Anchorage": "USA",
  "Pacific/Honolulu": "USA",
  "America/Toronto": "CAN",
  "America/Vancouver": "CAN",
  "America/Edmonton": "CAN",
  "America/Winnipeg": "CAN",
  "America/Halifax": "CAN",
  "America/Sao_Paulo": "BRA",
  "America/Fortaleza": "BRA",
  "America/Manaus": "BRA",
  "America/Mexico_City": "MEX",
  "America/Monterrey": "MEX",
  "America/Buenos_Aires": "ARG",
  "America/Argentina/Buenos_Aires": "ARG",
  "America/Bogota": "COL",
  "America/Santiago": "CHL",
  "America/Lima": "PER",
  "America/Guayaquil": "ECU",
  "America/Montevideo": "URY",
  "America/Costa_Rica": "CRI",
  "America/Guatemala": "GTM",
  "America/Panama": "PAN",
  "America/Puerto_Rico": "USA",
  "Asia/Tokyo": "JPN",
  "Asia/Seoul": "KOR",
  "Asia/Shanghai": "CHN",
  "Asia/Hong_Kong": "CHN",
  "Asia/Taipei": "TWN",
  "Asia/Singapore": "MYS",
  "Asia/Kolkata": "IND",
  "Asia/Calcutta": "IND",
  "Asia/Jakarta": "IDN",
  "Asia/Bangkok": "THA",
  "Asia/Ho_Chi_Minh": "VNM",
  "Asia/Manila": "PHL",
  "Asia/Kuala_Lumpur": "MYS",
  "Asia/Karachi": "PAK",
  "Asia/Dhaka": "BGD",
  "Asia/Colombo": "LKA",
  "Asia/Kathmandu": "NPL",
  "Asia/Phnom_Penh": "KHM",
  "Asia/Almaty": "KAZ",
  "Australia/Sydney": "AUS",
  "Australia/Melbourne": "AUS",
  "Australia/Brisbane": "AUS",
  "Australia/Perth": "AUS",
  "Australia/Adelaide": "AUS",
  "Pacific/Auckland": "NZL",
  "Asia/Dubai": "ARE",
  "Asia/Qatar": "QAT",
  "Asia/Kuwait": "KWT",
  "Asia/Riyadh": "SAU",
  "Asia/Amman": "JOR",
  "Asia/Beirut": "LBN",
  "Asia/Jerusalem": "ISR",
  "Asia/Tehran": "IRN",
  "Africa/Cairo": "EGY",
  "Africa/Johannesburg": "ZAF",
  "Africa/Lagos": "NGA",
  "Africa/Nairobi": "KEN",
  "Africa/Casablanca": "MAR",
  "Africa/Accra": "GHA",
  "Africa/Dar_es_Salaam": "TZA",
  "Africa/Kampala": "UGA",
  "Africa/Dakar": "SEN",
  "Africa/Abidjan": "CIV",
  "Africa/Tunis": "TUN",
};

const REGION_TO_ISO3: Record<string, string> = {
  US: "USA",
  GB: "GBR",
  UK: "GBR",
  DE: "DEU",
  FR: "FRA",
  HR: "HRV",
  IT: "ITA",
  ES: "ESP",
  NL: "NLD",
  PL: "POL",
  CA: "CAN",
  AU: "AUS",
  JP: "JPN",
  KR: "KOR",
  BR: "BRA",
  IN: "IND",
  MX: "MEX",
  AR: "ARG",
  SE: "SWE",
  NO: "NOR",
  DK: "DNK",
  FI: "FIN",
  CH: "CHE",
  AT: "AUT",
  BE: "BEL",
  IE: "IRL",
  PT: "PRT",
  CZ: "CZE",
  RO: "ROU",
  HU: "HUN",
  GR: "GRC",
  TR: "TUR",
  IL: "ISR",
  AE: "ARE",
  NZ: "NZL",
  ZA: "ZAF",
  NG: "NGA",
  EG: "EGY",
  KE: "KEN",
  ID: "IDN",
  TH: "THA",
  VN: "VNM",
  PH: "PHL",
  MY: "MYS",
  CN: "CHN",
  TW: "TWN",
  UA: "UKR",
  RS: "SRB",
  SI: "SVN",
  SK: "SVK",
  BG: "BGR",
  LT: "LTU",
  LV: "LVA",
  EE: "EST",
  LU: "LUX",
  IS: "ISL",
  CL: "CHL",
  CO: "COL",
  PE: "PER",
};

function fromIso3(iso3: string | undefined): Origin | null {
  if (!iso3) return null;
  const row: CountryMeta | undefined = CATALOG_BY_ISO3.get(iso3);
  if (row) return { iso3: row.iso3, name: row.name };
  return null;
}

export function inferOrigin(): Origin | null {
  if (typeof Intl === "undefined") return null;
  try {
    const tz = Intl.DateTimeFormat().resolvedOptions().timeZone;
    const fromTz = fromIso3(TZ_TO_ISO3[tz]);
    if (fromTz) return fromTz;
  } catch {
    /* ignore */
  }
  if (typeof navigator === "undefined") return null;
  const locale = navigator.language || "";
  const region = locale.split("-")[1]?.toUpperCase();
  return fromIso3(REGION_TO_ISO3[region ?? ""]);
}
