/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReferenceRouteImport } from './routes/api-reference'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as ExplorerRouteImport } from './routes/explorer'
import { Route as FaucetRouteImport } from './routes/faucet'
import { Route as HtlcRouteImport } from './routes/htlc'
import { Route as MapRouteImport } from './routes/map'
import { Route as MultiAssetRouteImport } from './routes/multi-asset'
import { Route as MultisigRouteImport } from './routes/multisig'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as NftRouteImport } from './routes/nft'
import { Route as PoolRouteImport } from './routes/pool'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as StealthRouteImport } from './routes/stealth'
import { Route as VaultsRouteImport } from './routes/vaults'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as ApiSplatRouteImport } from './routes/api/$'
import { Route as DownloadSplatRouteImport } from './routes/download/$'
import { Route as WalletAtomicSwapRouteImport } from './routes/wallet/atomic-swap'
import { Route as WalletCoinjoinRouteImport } from './routes/wallet/coinjoin'
import { Route as WalletRwaIssueRouteImport } from './routes/wallet/rwa-issue'
import { Route as ExplorerRwaAssetIdRouteImport } from './routes/explorer/rwa.$assetId'
import { Route as WalletCollectionCollectionIdRouteImport } from './routes/wallet/collection.$collectionId'
import { Route as WalletNftAssetIdRouteImport } from './routes/wallet/nft.$assetId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: '/api-reference',
  path: '/api-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorerRoute = ExplorerRouteImport.update({
  id: '/explorer',
  path: '/explorer',
  getParentRoute: () => rootRouteImport,
} as any)
const FaucetRoute = FaucetRouteImport.update({
  id: '/faucet',
  path: '/faucet',
  getParentRoute: () => rootRouteImport,
} as any)
const HtlcRoute = HtlcRouteImport.update({
  id: '/htlc',
  path: '/htlc',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const MultiAssetRoute = MultiAssetRouteImport.update({
  id: '/multi-asset',
  path: '/multi-asset',
  getParentRoute: () => rootRouteImport,
} as any)
const MultisigRoute = MultisigRouteImport.update({
  id: '/multisig',
  path: '/multisig',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const NftRoute = NftRouteImport.update({
  id: '/nft',
  path: '/nft',
  getParentRoute: () => rootRouteImport,
} as any)
const PoolRoute = PoolRouteImport.update({
  id: '/pool',
  path: '/pool',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const StealthRoute = StealthRouteImport.update({
  id: '/stealth',
  path: '/stealth',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultsRoute = VaultsRouteImport.update({
  id: '/vaults',
  path: '/vaults',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSplatRoute = ApiSplatRouteImport.update({
  id: '/api/$',
  path: '/api/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadSplatRoute = DownloadSplatRouteImport.update({
  id: '/download/$',
  path: '/download/$',
  getParentRoute: () => rootRouteImport,
} as any)
const WalletAtomicSwapRoute = WalletAtomicSwapRouteImport.update({
  id: '/atomic-swap',
  path: '/atomic-swap',
  getParentRoute: () => WalletRoute,
} as any)
const WalletCoinjoinRoute = WalletCoinjoinRouteImport.update({
  id: '/coinjoin',
  path: '/coinjoin',
  getParentRoute: () => WalletRoute,
} as any)
const WalletRwaIssueRoute = WalletRwaIssueRouteImport.update({
  id: '/rwa-issue',
  path: '/rwa-issue',
  getParentRoute: () => WalletRoute,
} as any)
const ExplorerRwaAssetIdRoute = ExplorerRwaAssetIdRouteImport.update({
  id: '/rwa/$assetId',
  path: '/rwa/$assetId',
  getParentRoute: () => ExplorerRoute,
} as any)
const WalletCollectionCollectionIdRoute =
  WalletCollectionCollectionIdRouteImport.update({
    id: '/collection/$collectionId',
    path: '/collection/$collectionId',
    getParentRoute: () => WalletRoute,
  } as any)
const WalletNftAssetIdRoute = WalletNftAssetIdRouteImport.update({
  id: '/nft/$assetId',
  path: '/nft/$assetId',
  getParentRoute: () => WalletRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api-reference': typeof ApiReferenceRoute
  '/docs': typeof DocsRoute
  '/explorer': typeof ExplorerRouteWithChildren
  '/faucet': typeof FaucetRoute
  '/htlc': typeof HtlcRoute
  '/map': typeof MapRoute
  '/multi-asset': typeof MultiAssetRoute
  '/multisig': typeof MultisigRoute
  '/network': typeof NetworkRoute
  '/nft': typeof NftRoute
  '/pool': typeof PoolRoute
  '/roadmap': typeof RoadmapRoute
  '/stealth': typeof StealthRoute
  '/vaults': typeof VaultsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/download/$': typeof DownloadSplatRoute
  '/wallet/atomic-swap': typeof WalletAtomicSwapRoute
  '/wallet/coinjoin': typeof WalletCoinjoinRoute
  '/wallet/rwa-issue': typeof WalletRwaIssueRoute
  '/explorer/rwa/$assetId': typeof ExplorerRwaAssetIdRoute
  '/wallet/collection/$collectionId': typeof WalletCollectionCollectionIdRoute
  '/wallet/nft/$assetId': typeof WalletNftAssetIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api-reference': typeof ApiReferenceRoute
  '/docs': typeof DocsRoute
  '/explorer': typeof ExplorerRouteWithChildren
  '/faucet': typeof FaucetRoute
  '/htlc': typeof HtlcRoute
  '/map': typeof MapRoute
  '/multi-asset': typeof MultiAssetRoute
  '/multisig': typeof MultisigRoute
  '/network': typeof NetworkRoute
  '/nft': typeof NftRoute
  '/pool': typeof PoolRoute
  '/roadmap': typeof RoadmapRoute
  '/stealth': typeof StealthRoute
  '/vaults': typeof VaultsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/download/$': typeof DownloadSplatRoute
  '/wallet/atomic-swap': typeof WalletAtomicSwapRoute
  '/wallet/coinjoin': typeof WalletCoinjoinRoute
  '/wallet/rwa-issue': typeof WalletRwaIssueRoute
  '/explorer/rwa/$assetId': typeof ExplorerRwaAssetIdRoute
  '/wallet/collection/$collectionId': typeof WalletCollectionCollectionIdRoute
  '/wallet/nft/$assetId': typeof WalletNftAssetIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api-reference': typeof ApiReferenceRoute
  '/docs': typeof DocsRoute
  '/explorer': typeof ExplorerRouteWithChildren
  '/faucet': typeof FaucetRoute
  '/htlc': typeof HtlcRoute
  '/map': typeof MapRoute
  '/multi-asset': typeof MultiAssetRoute
  '/multisig': typeof MultisigRoute
  '/network': typeof NetworkRoute
  '/nft': typeof NftRoute
  '/pool': typeof PoolRoute
  '/roadmap': typeof RoadmapRoute
  '/stealth': typeof StealthRoute
  '/vaults': typeof VaultsRoute
  '/wallet': typeof WalletRouteWithChildren
  '/api/$': typeof ApiSplatRoute
  '/download/$': typeof DownloadSplatRoute
  '/wallet/atomic-swap': typeof WalletAtomicSwapRoute
  '/wallet/coinjoin': typeof WalletCoinjoinRoute
  '/wallet/rwa-issue': typeof WalletRwaIssueRoute
  '/explorer/rwa/$assetId': typeof ExplorerRwaAssetIdRoute
  '/wallet/collection/$collectionId': typeof WalletCollectionCollectionIdRoute
  '/wallet/nft/$assetId': typeof WalletNftAssetIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api-reference'
    | '/docs'
    | '/explorer'
    | '/faucet'
    | '/htlc'
    | '/map'
    | '/multi-asset'
    | '/multisig'
    | '/network'
    | '/nft'
    | '/pool'
    | '/roadmap'
    | '/stealth'
    | '/vaults'
    | '/wallet'
    | '/api/$'
    | '/download/$'
    | '/wallet/atomic-swap'
    | '/wallet/coinjoin'
    | '/wallet/rwa-issue'
    | '/explorer/rwa/$assetId'
    | '/wallet/collection/$collectionId'
    | '/wallet/nft/$assetId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api-reference'
    | '/docs'
    | '/explorer'
    | '/faucet'
    | '/htlc'
    | '/map'
    | '/multi-asset'
    | '/multisig'
    | '/network'
    | '/nft'
    | '/pool'
    | '/roadmap'
    | '/stealth'
    | '/vaults'
    | '/wallet'
    | '/api/$'
    | '/download/$'
    | '/wallet/atomic-swap'
    | '/wallet/coinjoin'
    | '/wallet/rwa-issue'
    | '/explorer/rwa/$assetId'
    | '/wallet/collection/$collectionId'
    | '/wallet/nft/$assetId'
  id:
    | '__root__'
    | '/'
    | '/api-reference'
    | '/docs'
    | '/explorer'
    | '/faucet'
    | '/htlc'
    | '/map'
    | '/multi-asset'
    | '/multisig'
    | '/network'
    | '/nft'
    | '/pool'
    | '/roadmap'
    | '/stealth'
    | '/vaults'
    | '/wallet'
    | '/api/$'
    | '/download/$'
    | '/wallet/atomic-swap'
    | '/wallet/coinjoin'
    | '/wallet/rwa-issue'
    | '/explorer/rwa/$assetId'
    | '/wallet/collection/$collectionId'
    | '/wallet/nft/$assetId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiReferenceRoute: typeof ApiReferenceRoute
  DocsRoute: typeof DocsRoute
  ExplorerRoute: typeof ExplorerRouteWithChildren
  FaucetRoute: typeof FaucetRoute
  HtlcRoute: typeof HtlcRoute
  MapRoute: typeof MapRoute
  MultiAssetRoute: typeof MultiAssetRoute
  MultisigRoute: typeof MultisigRoute
  NetworkRoute: typeof NetworkRoute
  NftRoute: typeof NftRoute
  PoolRoute: typeof PoolRoute
  RoadmapRoute: typeof RoadmapRoute
  StealthRoute: typeof StealthRoute
  VaultsRoute: typeof VaultsRoute
  WalletRoute: typeof WalletRouteWithChildren
  ApiSplatRoute: typeof ApiSplatRoute
  DownloadSplatRoute: typeof DownloadSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api-reference': {
      id: '/api-reference'
      path: '/api-reference'
      fullPath: '/api-reference'
      preLoaderRoute: typeof ApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explorer': {
      id: '/explorer'
      path: '/explorer'
      fullPath: '/explorer'
      preLoaderRoute: typeof ExplorerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faucet': {
      id: '/faucet'
      path: '/faucet'
      fullPath: '/faucet'
      preLoaderRoute: typeof FaucetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/htlc': {
      id: '/htlc'
      path: '/htlc'
      fullPath: '/htlc'
      preLoaderRoute: typeof HtlcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multi-asset': {
      id: '/multi-asset'
      path: '/multi-asset'
      fullPath: '/multi-asset'
      preLoaderRoute: typeof MultiAssetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/multisig': {
      id: '/multisig'
      path: '/multisig'
      fullPath: '/multisig'
      preLoaderRoute: typeof MultisigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nft': {
      id: '/nft'
      path: '/nft'
      fullPath: '/nft'
      preLoaderRoute: typeof NftRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pool': {
      id: '/pool'
      path: '/pool'
      fullPath: '/pool'
      preLoaderRoute: typeof PoolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stealth': {
      id: '/stealth'
      path: '/stealth'
      fullPath: '/stealth'
      preLoaderRoute: typeof StealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vaults': {
      id: '/vaults'
      path: '/vaults'
      fullPath: '/vaults'
      preLoaderRoute: typeof VaultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/$': {
      id: '/api/$'
      path: '/api/$'
      fullPath: '/api/$'
      preLoaderRoute: typeof ApiSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/$': {
      id: '/download/$'
      path: '/download/$'
      fullPath: '/download/$'
      preLoaderRoute: typeof DownloadSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wallet/atomic-swap': {
      id: '/wallet/atomic-swap'
      path: '/atomic-swap'
      fullPath: '/wallet/atomic-swap'
      preLoaderRoute: typeof WalletAtomicSwapRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/coinjoin': {
      id: '/wallet/coinjoin'
      path: '/coinjoin'
      fullPath: '/wallet/coinjoin'
      preLoaderRoute: typeof WalletCoinjoinRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/rwa-issue': {
      id: '/wallet/rwa-issue'
      path: '/rwa-issue'
      fullPath: '/wallet/rwa-issue'
      preLoaderRoute: typeof WalletRwaIssueRouteImport
      parentRoute: typeof WalletRoute
    }
    '/explorer/rwa/$assetId': {
      id: '/explorer/rwa/$assetId'
      path: '/rwa/$assetId'
      fullPath: '/explorer/rwa/$assetId'
      preLoaderRoute: typeof ExplorerRwaAssetIdRouteImport
      parentRoute: typeof ExplorerRoute
    }
    '/wallet/collection/$collectionId': {
      id: '/wallet/collection/$collectionId'
      path: '/collection/$collectionId'
      fullPath: '/wallet/collection/$collectionId'
      preLoaderRoute: typeof WalletCollectionCollectionIdRouteImport
      parentRoute: typeof WalletRoute
    }
    '/wallet/nft/$assetId': {
      id: '/wallet/nft/$assetId'
      path: '/nft/$assetId'
      fullPath: '/wallet/nft/$assetId'
      preLoaderRoute: typeof WalletNftAssetIdRouteImport
      parentRoute: typeof WalletRoute
    }
  }
}

interface ExplorerRouteChildren {
  ExplorerRwaAssetIdRoute: typeof ExplorerRwaAssetIdRoute
}

const ExplorerRouteChildren: ExplorerRouteChildren = {
  ExplorerRwaAssetIdRoute: ExplorerRwaAssetIdRoute,
}

const ExplorerRouteWithChildren = ExplorerRoute._addFileChildren(
  ExplorerRouteChildren,
)

interface WalletRouteChildren {
  WalletAtomicSwapRoute: typeof WalletAtomicSwapRoute
  WalletCoinjoinRoute: typeof WalletCoinjoinRoute
  WalletRwaIssueRoute: typeof WalletRwaIssueRoute
  WalletCollectionCollectionIdRoute: typeof WalletCollectionCollectionIdRoute
  WalletNftAssetIdRoute: typeof WalletNftAssetIdRoute
}

const WalletRouteChildren: WalletRouteChildren = {
  WalletAtomicSwapRoute: WalletAtomicSwapRoute,
  WalletCoinjoinRoute: WalletCoinjoinRoute,
  WalletRwaIssueRoute: WalletRwaIssueRoute,
  WalletCollectionCollectionIdRoute: WalletCollectionCollectionIdRoute,
  WalletNftAssetIdRoute: WalletNftAssetIdRoute,
}

const WalletRouteWithChildren =
  WalletRoute._addFileChildren(WalletRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiReferenceRoute: ApiReferenceRoute,
  DocsRoute: DocsRoute,
  ExplorerRoute: ExplorerRouteWithChildren,
  FaucetRoute: FaucetRoute,
  HtlcRoute: HtlcRoute,
  MapRoute: MapRoute,
  MultiAssetRoute: MultiAssetRoute,
  MultisigRoute: MultisigRoute,
  NetworkRoute: NetworkRoute,
  NftRoute: NftRoute,
  PoolRoute: PoolRoute,
  RoadmapRoute: RoadmapRoute,
  StealthRoute: StealthRoute,
  VaultsRoute: VaultsRoute,
  WalletRoute: WalletRouteWithChildren,
  ApiSplatRoute: ApiSplatRoute,
  DownloadSplatRoute: DownloadSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
